import {
  ArrowDownRight,
  CheckCircle2,
  ShieldCheck,
} from "lucide-react";

import type { BorrowerAnalysisResult } from "../engine/borrowerAnalyzer";

interface PlanComparisonProps {
  analysis: BorrowerAnalysisResult;
}

function formatCurrency(value: number) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);
}

export default function PlanComparison({
  analysis,
}: PlanComparisonProps) {
  const requestedAmount =
    analysis.requestedLoan.amount;

  const recommendedAmount =
    analysis.decision.recommendedLoanAmount;

  const requestedEmi =
    analysis.requestedLoan.monthlyEmi;

  const safeEmi =
    analysis.affordability.safeMonthlyEmi;

  const amountDifference = Math.max(
    requestedAmount - recommendedAmount,
    0,
  );

  const emiDifference = Math.max(
    requestedEmi - safeEmi,
    0,
  );

  const isAlreadySafe =
    analysis.decision.recommendation ===
    "BORROW";

  return (
    <section className="fintech-card rounded-[26px] p-6 sm:p-7">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#A66A96]">
            Plan intelligence
          </p>

          <h2 className="mt-2 text-xl font-semibold">
            Requested plan vs safer plan
          </h2>

          <p className="mt-2 max-w-2xl text-sm leading-6 text-[#817783]">
            A side-by-side view of your current request and
            the amount generated by the existing affordability
            logic.
          </p>
        </div>

        <span
          className={`inline-flex w-fit items-center gap-2 rounded-full border px-3 py-1.5 text-[10px] font-bold tracking-[0.1em] ${
            isAlreadySafe
              ? "border-[#39D39F]/20 bg-[#39D39F]/10 text-[#39D39F]"
              : "border-[#A66A96]/20 bg-[#A66A96]/10 text-[#D5A9CA]"
          }`}
        >
          {isAlreadySafe ? (
            <CheckCircle2 size={14} />
          ) : (
            <ShieldCheck size={14} />
          )}

          {isAlreadySafe
            ? "WITHIN RANGE"
            : "SAFER ALTERNATIVE"}
        </span>
      </div>

      <div className="mt-7 grid gap-4 md:grid-cols-2">
        <PlanBox
          title="Your requested plan"
          amount={requestedAmount}
          emi={requestedEmi}
        />

        <PlanBox
          title="Assessed safer plan"
          amount={recommendedAmount}
          emi={safeEmi}
          featured
        />
      </div>

      {!isAlreadySafe && (
        <div className="mt-4 flex gap-3 rounded-2xl border border-[#E7A84B]/15 bg-[#E7A84B]/[0.05] p-4">
          <ArrowDownRight
            size={18}
            className="mt-0.5 shrink-0 text-[#E7A84B]"
          />

          <div>
            <p className="text-sm font-semibold text-[#E7D0A4]">
              What changes?
            </p>

            <div className="mt-1 space-y-1 text-sm leading-6 text-[#A59AA4]">
              {amountDifference > 0 && (
                <p>
                  Borrow{" "}
                  {formatCurrency(amountDifference)}{" "}
                  less.
                </p>
              )}

              {emiDifference > 0 && (
                <p>
                  Reduce monthly EMI pressure by{" "}
                  {formatCurrency(emiDifference)}.
                </p>
              )}
            </div>
          </div>
        </div>
      )}
    </section>
  );
}

function PlanBox({
  title,
  amount,
  emi,
  featured = false,
}: {
  title: string;
  amount: number;
  emi: number;
  featured?: boolean;
}) {
  return (
    <div
      className={`rounded-2xl border p-5 ${
        featured
          ? "border-[#8A4D7B]/25 bg-gradient-to-br from-[#211521] to-[#120E13]"
          : "border-white/[0.07] bg-white/[0.025]"
      }`}
    >
      <p
        className={`text-[10px] font-bold uppercase tracking-[0.13em] ${
          featured
            ? "text-[#D5A9CA]"
            : "text-[#716873]"
        }`}
      >
        {title}
      </p>

      <div className="mt-6 grid grid-cols-2 gap-4">
        <div>
          <p className="text-xs text-[#716873]">
            Loan amount
          </p>

          <p className="fintech-number mt-1 text-xl font-semibold">
            {formatCurrency(amount)}
          </p>
        </div>

        <div>
          <p className="text-xs text-[#716873]">
            Monthly EMI
          </p>

          <p
            className={`fintech-number mt-1 text-xl font-semibold ${
              featured
                ? "text-[#D5A9CA]"
                : "text-[#E5DEE3]"
            }`}
          >
            {formatCurrency(emi)}
          </p>
        </div>
      </div>
    </div>
  );
}